
package frc.robot.util;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BlueRightManeuverR = new ChoreoTraj(
	    "BlueRightManeuverR",
	    OptionalInt.empty(),
	    1.77962,
	    new Pose2d(3.551, 1.176, Rotation2d.fromRadians(0)),
	    new Pose2d(3.536, 2.525, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftIntakeMR = new ChoreoTraj(
	    "BlueLeftIntakeMR",
	    OptionalInt.empty(),
	    3.22093,
	    new Pose2d(5.663, 5.416, Rotation2d.fromRadians(0)),
	    new Pose2d(5.663, 5.404, Rotation2d.fromRadians(-3.134))
	);
	public static final ChoreoTraj RedDepotM = new ChoreoTraj(
	    "RedDepotM",
	    OptionalInt.empty(),
	    3.85455,
	    new Pose2d(13.01, 4.014, Rotation2d.fromRadians(0)),
	    new Pose2d(14.479, 2.059, Rotation2d.fromRadians(1.567))
	);
	public static final ChoreoTraj RedLeftClimbR = new ChoreoTraj(
	    "RedLeftClimbR",
	    OptionalInt.empty(),
	    0.9878,
	    new Pose2d(13.543, 3.281, Rotation2d.fromRadians(2.563)),
	    new Pose2d(14.823, 4.75, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedRightIntakeMR = new ChoreoTraj(
	    "RedRightIntakeMR",
	    OptionalInt.empty(),
	    3.22263,
	    new Pose2d(10.889, 5.486, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.897, 5.486, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedOutpostToShoot = new ChoreoTraj(
	    "RedOutpostToShoot",
	    OptionalInt.empty(),
	    1.38592,
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0)),
	    new Pose2d(13.433, 4.802, Rotation2d.fromRadians(-2.617))
	);
	public static final ChoreoTraj BlueRightIntakeM = new ChoreoTraj(
	    "BlueRightIntakeM",
	    OptionalInt.empty(),
	    3.33047,
	    new Pose2d(5.645, 2.555, Rotation2d.fromRadians(0)),
	    new Pose2d(5.66, 2.551, Rotation2d.fromRadians(-3.142))
	);
	public static final ChoreoTraj BlueLeftClimbR = new ChoreoTraj(
	    "BlueLeftClimbR",
	    OptionalInt.empty(),
	    1.04182,
	    new Pose2d(3.06, 5.008, Rotation2d.fromRadians(-0.712)),
	    new Pose2d(1.703, 3.317, Rotation2d.fromRadians(-3.137))
	);
	public static final ChoreoTraj BlueRightIntakeMR = new ChoreoTraj(
	    "BlueRightIntakeMR",
	    OptionalInt.empty(),
	    3.18818,
	    new Pose2d(5.683, 2.465, Rotation2d.fromRadians(0)),
	    new Pose2d(5.674, 2.455, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftIntakeR = new ChoreoTraj(
	    "RedLeftIntakeR",
	    OptionalInt.empty(),
	    3.94394,
	    new Pose2d(10.887, 2.586, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.884, 2.563, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftIntakeR = new ChoreoTraj(
	    "BlueLeftIntakeR",
	    OptionalInt.empty(),
	    3.92087,
	    new Pose2d(5.658, 5.478, Rotation2d.fromRadians(0)),
	    new Pose2d(5.658, 5.477, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj BlueRightIntakeL = new ChoreoTraj(
	    "BlueRightIntakeL",
	    OptionalInt.empty(),
	    3.6665,
	    new Pose2d(5.657, 2.542, Rotation2d.fromRadians(0)),
	    new Pose2d(5.657, 2.542, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftShoot = new ChoreoTraj(
	    "RedLeftShoot",
	    OptionalInt.empty(),
	    0.79837,
	    new Pose2d(12.992, 2.508, Rotation2d.fromRadians(0)),
	    new Pose2d(13.543, 3.281, Rotation2d.fromRadians(2.563))
	);
	public static final ChoreoTraj BlueOutpostR = new ChoreoTraj(
	    "BlueOutpostR",
	    OptionalInt.empty(),
	    1.24902,
	    new Pose2d(3.541, 0.667, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.449, 0.652, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedDepotL = new ChoreoTraj(
	    "RedDepotL",
	    OptionalInt.empty(),
	    3.66011,
	    new Pose2d(13.482, 3.053, Rotation2d.fromRadians(2.491)),
	    new Pose2d(14.532, 2.07, Rotation2d.fromRadians(1.584))
	);
	public static final ChoreoTraj MoveRightWithMarker = new ChoreoTraj(
	    "MoveRightWithMarker",
	    OptionalInt.empty(),
	    2.94281,
	    new Pose2d(14.634, 3.899, Rotation2d.fromRadians(-0.032)),
	    new Pose2d(14.626, 4.87, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedDepotR = new ChoreoTraj(
	    "RedDepotR",
	    OptionalInt.empty(),
	    3.57534,
	    new Pose2d(13.394, 5.03, Rotation2d.fromRadians(-2.63)),
	    new Pose2d(14.487, 2.089, Rotation2d.fromRadians(1.586))
	);
	public static final ChoreoTraj RedOutpostToShootShort = new ChoreoTraj(
	    "RedOutpostToShootShort",
	    OptionalInt.empty(),
	    1.16243,
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0)),
	    new Pose2d(14.212, 5.472, Rotation2d.fromRadians(-2.523))
	);
	public static final ChoreoTraj BlueRightIntakeSweepShort = new ChoreoTraj(
	    "BlueRightIntakeSweepShort",
	    OptionalInt.empty(),
	    2.78601,
	    new Pose2d(5.671, 2.587, Rotation2d.fromRadians(0)),
	    new Pose2d(5.671, 2.587, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj BlueLeftIntakeL = new ChoreoTraj(
	    "BlueLeftIntakeL",
	    OptionalInt.empty(),
	    3.52242,
	    new Pose2d(5.671, 5.646, Rotation2d.fromRadians(0)),
	    new Pose2d(5.671, 5.646, Rotation2d.fromRadians(-3.142))
	);
	public static final ChoreoTraj RedLeftIntakeL = new ChoreoTraj(
	    "RedLeftIntakeL",
	    OptionalInt.empty(),
	    2.94293,
	    new Pose2d(10.853, 2.568, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.862, 2.568, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedRightIntakeSweepShort = new ChoreoTraj(
	    "RedRightIntakeSweepShort",
	    OptionalInt.empty(),
	    2.96788,
	    new Pose2d(10.887, 5.429, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.879, 5.421, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueRightIntakeR = new ChoreoTraj(
	    "BlueRightIntakeR",
	    OptionalInt.empty(),
	    3.39471,
	    new Pose2d(5.666, 2.575, Rotation2d.fromRadians(0)),
	    new Pose2d(5.672, 2.569, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj BlueDepotToShoot = new ChoreoTraj(
	    "BlueDepotToShoot",
	    OptionalInt.empty(),
	    0.85322,
	    new Pose2d(1.98, 5.928, Rotation2d.fromRadians(-1.57)),
	    new Pose2d(3.188, 4.573, Rotation2d.fromRadians(-0.552))
	);
	public static final ChoreoTraj BlueOutpostL = new ChoreoTraj(
	    "BlueOutpostL",
	    OptionalInt.empty(),
	    1.55686,
	    new Pose2d(3.555, 3.85, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.447, 0.667, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftIntakeSweepShort = new ChoreoTraj(
	    "RedLeftIntakeSweepShort",
	    OptionalInt.empty(),
	    3.1127,
	    new Pose2d(10.899, 2.43, Rotation2d.fromRadians(-3.137)),
	    new Pose2d(10.892, 2.431, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueOutpostM = new ChoreoTraj(
	    "BlueOutpostM",
	    OptionalInt.empty(),
	    1.35172,
	    new Pose2d(3.555, 2.414, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.447, 0.667, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftIntakeM = new ChoreoTraj(
	    "RedLeftIntakeM",
	    OptionalInt.empty(),
	    2.84302,
	    new Pose2d(10.877, 2.552, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.865, 2.552, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftClimbL = new ChoreoTraj(
	    "BlueLeftClimbL",
	    OptionalInt.empty(),
	    0.83207,
	    new Pose2d(2.943, 4.884, Rotation2d.fromRadians(-0.712)),
	    new Pose2d(1.764, 4.164, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj RedRightShoot = new ChoreoTraj(
	    "RedRightShoot",
	    OptionalInt.empty(),
	    0.90961,
	    new Pose2d(12.991, 5.556, Rotation2d.fromRadians(0)),
	    new Pose2d(13.741, 4.784, Rotation2d.fromRadians(-2.717))
	);
	public static final ChoreoTraj BlueLeftIntakeM = new ChoreoTraj(
	    "BlueLeftIntakeM",
	    OptionalInt.empty(),
	    2.82361,
	    new Pose2d(5.67, 5.517, Rotation2d.fromRadians(0)),
	    new Pose2d(5.67, 5.506, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj BlueRightIntakeML = new ChoreoTraj(
	    "BlueRightIntakeML",
	    OptionalInt.empty(),
	    3.62103,
	    new Pose2d(5.66, 2.548, Rotation2d.fromRadians(0)),
	    new Pose2d(5.681, 2.548, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj BlueLeftIntakeML = new ChoreoTraj(
	    "BlueLeftIntakeML",
	    OptionalInt.empty(),
	    3.2239,
	    new Pose2d(5.66, 5.56, Rotation2d.fromRadians(0)),
	    new Pose2d(5.692, 5.56, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj BlueRightManeuverL = new ChoreoTraj(
	    "BlueRightManeuverL",
	    OptionalInt.empty(),
	    1.5941,
	    new Pose2d(3.559, 3.854, Rotation2d.fromRadians(0)),
	    new Pose2d(3.545, 2.462, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftIntakeSweepShort = new ChoreoTraj(
	    "BlueLeftIntakeSweepShort",
	    OptionalInt.empty(),
	    3.12101,
	    new Pose2d(5.673, 5.51, Rotation2d.fromRadians(0)),
	    new Pose2d(5.662, 5.51, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj MoveLeft = new ChoreoTraj(
	    "MoveLeft",
	    OptionalInt.empty(),
	    6.02199,
	    new Pose2d(13.611, 4.912, Rotation2d.fromRadians(3.133)),
	    new Pose2d(14.634, 3.899, Rotation2d.fromRadians(-0.032))
	);
	public static final ChoreoTraj RedLeftClimbL = new ChoreoTraj(
	    "RedLeftClimbL",
	    OptionalInt.empty(),
	    0.83868,
	    new Pose2d(13.543, 3.281, Rotation2d.fromRadians(2.563)),
	    new Pose2d(14.814, 3.881, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedRightIntakeML = new ChoreoTraj(
	    "RedRightIntakeML",
	    OptionalInt.empty(),
	    3.33027,
	    new Pose2d(10.869, 5.453, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.858, 5.442, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedDepotRDrake = new ChoreoTraj(
	    "RedDepotRDrake",
	    OptionalInt.empty(),
	    3.6321,
	    new Pose2d(13.006, 1.658, Rotation2d.fromRadians(3.142)),
	    new Pose2d(14.487, 2.089, Rotation2d.fromRadians(1.586))
	);
	public static final ChoreoTraj BlueRightShoot = new ChoreoTraj(
	    "BlueRightShoot",
	    OptionalInt.empty(),
	    0.92887,
	    new Pose2d(3.55, 2.501, Rotation2d.fromRadians(3.14)),
	    new Pose2d(2.901, 3.305, Rotation2d.fromRadians(0.421))
	);
	public static final ChoreoTraj RedRightIntakeL = new ChoreoTraj(
	    "RedRightIntakeL",
	    OptionalInt.empty(),
	    3.86878,
	    new Pose2d(10.852, 5.38, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.869, 5.378, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedLeftManeuverR = new ChoreoTraj(
	    "RedLeftManeuverR",
	    OptionalInt.empty(),
	    1.70291,
	    new Pose2d(12.986, 3.847, Rotation2d.fromRadians(3.142)),
	    new Pose2d(12.98, 2.501, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj BlueRightClimbL = new ChoreoTraj(
	    "BlueRightClimbL",
	    OptionalInt.empty(),
	    0.87061,
	    new Pose2d(3, 3.325, Rotation2d.fromRadians(0.421)),
	    new Pose2d(1.744, 4.169, Rotation2d.fromRadians(-3.133))
	);
	public static final ChoreoTraj RedRightClimbL = new ChoreoTraj(
	    "RedRightClimbL",
	    OptionalInt.empty(),
	    0.86432,
	    new Pose2d(13.577, 4.672, Rotation2d.fromRadians(-2.641)),
	    new Pose2d(14.852, 3.895, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedLeftIntakeSweep = new ChoreoTraj(
	    "RedLeftIntakeSweep",
	    OptionalInt.empty(),
	    3.6046,
	    new Pose2d(10.863, 2.422, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.877, 5.531, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedOutpostM = new ChoreoTraj(
	    "RedOutpostM",
	    OptionalInt.empty(),
	    1.57285,
	    new Pose2d(13.004, 4.032, Rotation2d.fromRadians(0)),
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedOutpostRDrake = new ChoreoTraj(
	    "RedOutpostRDrake",
	    OptionalInt.empty(),
	    1.28148,
	    new Pose2d(13.006, 6.421, Rotation2d.fromRadians(3.14)),
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftManeuverR = new ChoreoTraj(
	    "BlueLeftManeuverR",
	    OptionalInt.empty(),
	    1.7457,
	    new Pose2d(3.555, 4.227, Rotation2d.fromRadians(0)),
	    new Pose2d(3.539, 5.654, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueDepotM = new ChoreoTraj(
	    "BlueDepotM",
	    OptionalInt.empty(),
	    3.9506,
	    new Pose2d(3.562, 5.538, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.9, 5.965, Rotation2d.fromRadians(-1.577))
	);
	public static final ChoreoTraj BlueLeftShoot = new ChoreoTraj(
	    "BlueLeftShoot",
	    OptionalInt.empty(),
	    0.70973,
	    new Pose2d(3.55, 5.593, Rotation2d.fromRadians(3.14)),
	    new Pose2d(3.006, 4.902, Rotation2d.fromRadians(-0.712))
	);
	public static final ChoreoTraj BlueDepotL = new ChoreoTraj(
	    "BlueDepotL",
	    OptionalInt.empty(),
	    5.13068,
	    new Pose2d(3.084, 4.966, Rotation2d.fromRadians(-0.838)),
	    new Pose2d(1.878, 5.932, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj RedRightManeuverR = new ChoreoTraj(
	    "RedRightManeuverR",
	    OptionalInt.empty(),
	    1.64883,
	    new Pose2d(12.98, 6.893, Rotation2d.fromRadians(3.14)),
	    new Pose2d(12.999, 5.506, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftIntakeMR = new ChoreoTraj(
	    "RedLeftIntakeMR",
	    OptionalInt.empty(),
	    3.40387,
	    new Pose2d(10.87, 2.542, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.88, 2.542, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedOutpostL = new ChoreoTraj(
	    "RedOutpostL",
	    OptionalInt.empty(),
	    1.68038,
	    new Pose2d(13.459, 3.07, Rotation2d.fromRadians(2.465)),
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedRightIntakeSweep = new ChoreoTraj(
	    "RedRightIntakeSweep",
	    OptionalInt.empty(),
	    4.03014,
	    new Pose2d(10.863, 5.401, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.899, 2.43, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueOutpostToShoot = new ChoreoTraj(
	    "BlueOutpostToShoot",
	    OptionalInt.empty(),
	    1.44532,
	    new Pose2d(0.449, 0.652, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.205, 3.544, Rotation2d.fromRadians(0.289))
	);
	public static final ChoreoTraj p2Intake = new ChoreoTraj(
	    "p2Intake",
	    OptionalInt.empty(),
	    2.61352,
	    new Pose2d(5.639, 2.96, Rotation2d.fromRadians(1.595)),
	    new Pose2d(5.652, 2.96, Rotation2d.fromRadians(1.592))
	);
	public static final ChoreoTraj RedRightIntakeM = new ChoreoTraj(
	    "RedRightIntakeM",
	    OptionalInt.empty(),
	    2.81032,
	    new Pose2d(10.87, 5.533, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.87, 5.523, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RedRightManeuverL = new ChoreoTraj(
	    "RedRightManeuverL",
	    OptionalInt.empty(),
	    1.48767,
	    new Pose2d(12.984, 4.225, Rotation2d.fromRadians(3.142)),
	    new Pose2d(13.005, 5.506, Rotation2d.fromRadians(3.14))
	);
	public static final ChoreoTraj GoRight = new ChoreoTraj(
	    "GoRight",
	    OptionalInt.empty(),
	    12.41307,
	    new Pose2d(2.914, 7.367, Rotation2d.fromRadians(0)),
	    new Pose2d(2.965, 1.334, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueDepotR = new ChoreoTraj(
	    "BlueDepotR",
	    OptionalInt.empty(),
	    4.93201,
	    new Pose2d(2.924, 3.015, Rotation2d.fromRadians(0.606)),
	    new Pose2d(1.888, 5.955, Rotation2d.fromRadians(-1.589))
	);
	public static final ChoreoTraj BlueLeftIntakeSweep = new ChoreoTraj(
	    "BlueLeftIntakeSweep",
	    OptionalInt.empty(),
	    3.63065,
	    new Pose2d(5.673, 5.51, Rotation2d.fromRadians(0)),
	    new Pose2d(5.666, 2.519, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedLeftIntakeML = new ChoreoTraj(
	    "RedLeftIntakeML",
	    OptionalInt.empty(),
	    3.11748,
	    new Pose2d(10.87, 2.542, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.88, 2.523, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueRightIntakeSweep = new ChoreoTraj(
	    "BlueRightIntakeSweep",
	    OptionalInt.empty(),
	    3.70191,
	    new Pose2d(5.671, 2.587, Rotation2d.fromRadians(0)),
	    new Pose2d(5.666, 5.575, Rotation2d.fromRadians(-3.14))
	);
	public static final ChoreoTraj RedOutpostR = new ChoreoTraj(
	    "RedOutpostR",
	    OptionalInt.empty(),
	    1.38256,
	    new Pose2d(13.358, 4.904, Rotation2d.fromRadians(-2.532)),
	    new Pose2d(16.099, 7.401, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueLeftManeuverL = new ChoreoTraj(
	    "BlueLeftManeuverL",
	    OptionalInt.empty(),
	    1.56596,
	    new Pose2d(3.555, 6.886, Rotation2d.fromRadians(0)),
	    new Pose2d(3.542, 5.529, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj MoveLeftWithMarker = new ChoreoTraj(
	    "MoveLeftWithMarker",
	    OptionalInt.empty(),
	    6.02199,
	    new Pose2d(13.611, 4.912, Rotation2d.fromRadians(3.133)),
	    new Pose2d(14.634, 3.899, Rotation2d.fromRadians(-0.032))
	);
	public static final ChoreoTraj RedDepotToShoot = new ChoreoTraj(
	    "RedDepotToShoot",
	    OptionalInt.empty(),
	    0.93877,
	    new Pose2d(14.487, 2.089, Rotation2d.fromRadians(1.569)),
	    new Pose2d(13.339, 3.425, Rotation2d.fromRadians(2.806))
	);
	public static final ChoreoTraj RedRightIntakeR = new ChoreoTraj(
	    "RedRightIntakeR",
	    OptionalInt.empty(),
	    3.52607,
	    new Pose2d(10.89, 5.475, Rotation2d.fromRadians(3.14)),
	    new Pose2d(10.89, 5.484, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj MoveRight = new ChoreoTraj(
	    "MoveRight",
	    OptionalInt.empty(),
	    0.65548,
	    new Pose2d(14.626, 4.87, Rotation2d.fromRadians(0)),
	    new Pose2d(14.634, 3.899, Rotation2d.fromRadians(-0.032))
	);
	public static final ChoreoTraj RedLeftManeuverL = new ChoreoTraj(
	    "RedLeftManeuverL",
	    OptionalInt.empty(),
	    1.53926,
	    new Pose2d(12.976, 1.184, Rotation2d.fromRadians(3.142)),
	    new Pose2d(12.98, 2.501, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RedRightClimbR = new ChoreoTraj(
	    "RedRightClimbR",
	    OptionalInt.empty(),
	    0.82484,
	    new Pose2d(13.465, 4.698, Rotation2d.fromRadians(-2.641)),
	    new Pose2d(14.824, 4.735, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BlueRightClimbR = new ChoreoTraj(
	    "BlueRightClimbR",
	    OptionalInt.empty(),
	    0.79853,
	    new Pose2d(3, 3.325, Rotation2d.fromRadians(0.421)),
	    new Pose2d(1.727, 3.339, Rotation2d.fromRadians(-3.126))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("BlueRightManeuverR", BlueRightManeuverR),
		Map.entry("BlueLeftIntakeMR", BlueLeftIntakeMR),
		Map.entry("RedDepotM", RedDepotM),
		Map.entry("RedLeftClimbR", RedLeftClimbR),
		Map.entry("RedRightIntakeMR", RedRightIntakeMR),
		Map.entry("RedOutpostToShoot", RedOutpostToShoot),
		Map.entry("BlueRightIntakeM", BlueRightIntakeM),
		Map.entry("BlueLeftClimbR", BlueLeftClimbR),
		Map.entry("BlueRightIntakeMR", BlueRightIntakeMR),
		Map.entry("RedLeftIntakeR", RedLeftIntakeR),
		Map.entry("BlueLeftIntakeR", BlueLeftIntakeR),
		Map.entry("BlueRightIntakeL", BlueRightIntakeL),
		Map.entry("RedLeftShoot", RedLeftShoot),
		Map.entry("BlueOutpostR", BlueOutpostR),
		Map.entry("RedDepotL", RedDepotL),
		Map.entry("MoveRightWithMarker", MoveRightWithMarker),
		Map.entry("RedDepotR", RedDepotR),
		Map.entry("RedOutpostToShootShort", RedOutpostToShootShort),
		Map.entry("BlueRightIntakeSweepShort", BlueRightIntakeSweepShort),
		Map.entry("BlueLeftIntakeL", BlueLeftIntakeL),
		Map.entry("RedLeftIntakeL", RedLeftIntakeL),
		Map.entry("RedRightIntakeSweepShort", RedRightIntakeSweepShort),
		Map.entry("BlueRightIntakeR", BlueRightIntakeR),
		Map.entry("BlueDepotToShoot", BlueDepotToShoot),
		Map.entry("BlueOutpostL", BlueOutpostL),
		Map.entry("RedLeftIntakeSweepShort", RedLeftIntakeSweepShort),
		Map.entry("BlueOutpostM", BlueOutpostM),
		Map.entry("RedLeftIntakeM", RedLeftIntakeM),
		Map.entry("BlueLeftClimbL", BlueLeftClimbL),
		Map.entry("RedRightShoot", RedRightShoot),
		Map.entry("BlueLeftIntakeM", BlueLeftIntakeM),
		Map.entry("BlueRightIntakeML", BlueRightIntakeML),
		Map.entry("BlueLeftIntakeML", BlueLeftIntakeML),
		Map.entry("BlueRightManeuverL", BlueRightManeuverL),
		Map.entry("BlueLeftIntakeSweepShort", BlueLeftIntakeSweepShort),
		Map.entry("MoveLeft", MoveLeft),
		Map.entry("RedLeftClimbL", RedLeftClimbL),
		Map.entry("RedRightIntakeML", RedRightIntakeML),
		Map.entry("RedDepotRDrake", RedDepotRDrake),
		Map.entry("BlueRightShoot", BlueRightShoot),
		Map.entry("RedRightIntakeL", RedRightIntakeL),
		Map.entry("RedLeftManeuverR", RedLeftManeuverR),
		Map.entry("BlueRightClimbL", BlueRightClimbL),
		Map.entry("RedRightClimbL", RedRightClimbL),
		Map.entry("RedLeftIntakeSweep", RedLeftIntakeSweep),
		Map.entry("RedOutpostM", RedOutpostM),
		Map.entry("RedOutpostRDrake", RedOutpostRDrake),
		Map.entry("BlueLeftManeuverR", BlueLeftManeuverR),
		Map.entry("BlueDepotM", BlueDepotM),
		Map.entry("BlueLeftShoot", BlueLeftShoot),
		Map.entry("BlueDepotL", BlueDepotL),
		Map.entry("RedRightManeuverR", RedRightManeuverR),
		Map.entry("RedLeftIntakeMR", RedLeftIntakeMR),
		Map.entry("RedOutpostL", RedOutpostL),
		Map.entry("RedRightIntakeSweep", RedRightIntakeSweep),
		Map.entry("BlueOutpostToShoot", BlueOutpostToShoot),
		Map.entry("p2Intake", p2Intake),
		Map.entry("RedRightIntakeM", RedRightIntakeM),
		Map.entry("RedRightManeuverL", RedRightManeuverL),
		Map.entry("GoRight", GoRight),
		Map.entry("BlueDepotR", BlueDepotR),
		Map.entry("BlueLeftIntakeSweep", BlueLeftIntakeSweep),
		Map.entry("RedLeftIntakeML", RedLeftIntakeML),
		Map.entry("BlueRightIntakeSweep", BlueRightIntakeSweep),
		Map.entry("RedOutpostR", RedOutpostR),
		Map.entry("BlueLeftManeuverL", BlueLeftManeuverL),
		Map.entry("MoveLeftWithMarker", MoveLeftWithMarker),
		Map.entry("RedDepotToShoot", RedDepotToShoot),
		Map.entry("RedRightIntakeR", RedRightIntakeR),
		Map.entry("MoveRight", MoveRight),
		Map.entry("RedLeftManeuverL", RedLeftManeuverL),
		Map.entry("RedRightClimbR", RedRightClimbR),
		Map.entry("BlueRightClimbR", BlueRightClimbR)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
